### PR TITLE
Adds the metapackage generation steps

### PR DESCRIPTION
**Pull request by ryanaslett**
This generates the metapackages at both steps, in the proper order, and minimizes noise. 

I've tested this locally, manually, and it seems to do what its supposed to.

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
That's better.

I'm wondering if we should also run `composer update drupal/core` here as well, just in case the lock file is not up-to-date at release time?

**Comment by xjm** [comment]
Well, we don’t want extra diffs at time of release; the lock file SHOULD be
updated in the commit. It could get dicey especially if a
non-core-committer has to tag a security release, for example.

**Comment by ryanaslett** [comment]
I had a version of this file that printed the git diff right before each commit, and when I tested it locally, the changes were solely the version numbers. of drupal/core-recommended and drupal/core-dev-pinned.

I dont think this is the place for extra last minute fixes - ie. if the lock does update somebody would have to verify that was the desired behavior, and the changes were correct - thats not something we want to put on the release managers.  

I think a lockfile sync detection mechanism would be more appropriate for the d8 git hooks script that the core commiters use.

**Comment by xjm** [comment]
OK, going to merge this and test it out with today's release. Thanks!

**Pull request merged**
